import sqlalchemy as sq
import os
import tqdm

# update this path to point at a California ZAsmt database loaded to SQLite by ztraxdb
sqlite = sq.create_engine("sqlite:////Volumes/Pheasant Ridge/ztrax/ca.db")
postgres = sq.create_engine(os.environ["SQMAKE_DB"])

with sqlite.connect() as src:
    with postgres.connect() as dest:
        with postgres.begin() as trans:
            trans.execute("""
            CREATE TABLE diss.zasmt (
                "Main_ImportParcelID" BIGINT,
                "Main_FIPS" VARCHAR,
                "Main_State" VARCHAR,
                "Main_County" VARCHAR,
                "Main_ValueCertDate" DATE,
                "Main_ExtractDate" VARCHAR,
                "Main_Edition" INTEGER,
                "Main_ZVendorStndCode" VARCHAR,
                "Main_AssessorParcelNumber" VARCHAR,
                "Main_DupAPN" VARCHAR,
                "Main_UnformattedAssessorParcelNumber" VARCHAR,
                "Main_ParcelSequenceNumber" INTEGER,
                "Main_AlternateParcelNumber" VARCHAR,
                "Main_OldParcelNumber" VARCHAR,
                "Main_ParcelNumberTypeStndCode" VARCHAR,
                "Main_RecordSourceStndCode" VARCHAR,
                "Main_RecordTypeStndCode" VARCHAR,
                "Main_ConfidentialRecordFlag" VARCHAR,
                "Main_PropertyAddressSourceStndCode" VARCHAR,
                "Main_PropertyHouseNumber" VARCHAR,
                "Main_PropertyHouseNumberExt" VARCHAR,
                "Main_PropertyStreetPreDirectional" VARCHAR,
                "Main_PropertyStreetName" VARCHAR,
                "Main_PropertyStreetSuffix" VARCHAR,
                "Main_PropertyStreetPostDirectional" VARCHAR,
                "Main_PropertyFullStreetAddress" VARCHAR,
                "Main_PropertyCity" VARCHAR,
                "Main_PropertyState" VARCHAR,
                "Main_PropertyZip" VARCHAR,
                "Main_PropertyZip4" VARCHAR,
                "Main_OriginalPropertyFullStreetAddress" VARCHAR,
                "Main_OriginalPropertyAddressLastline" VARCHAR,
                "Main_PropertyBuildingNumber" VARCHAR,
                "Main_PropertyZoningDescription" VARCHAR,
                "Main_PropertyZoningSourceCode" VARCHAR,
                "Main_CensusTract" VARCHAR,
                "Main_TaxIDNumber" VARCHAR,
                "Main_TaxAmount" FLOAT,
                "Main_TaxYear" INTEGER,
                "Main_TaxDelinquencyFlag" VARCHAR,
                "Main_TaxDelinquencyAmount" FLOAT,
                "Main_TaxDelinquencyYear" INTEGER,
                "Main_TaxRateCodeArea" VARCHAR,
                "Main_LegalLot" VARCHAR,
                "Main_LegalLotStndCode" VARCHAR,
                "Main_LegalOtherLot" VARCHAR,
                "Main_LegalBlock" VARCHAR,
                "Main_LegalSubdivisionCode" VARCHAR,
                "Main_LegalSubdivisionName" VARCHAR,
                "Main_LegalCondoProjectPUDDevName" VARCHAR,
                "Main_LegalBuildingNumber" VARCHAR,
                "Main_LegalUnit" VARCHAR,
                "Main_LegalSection" VARCHAR,
                "Main_LegalPhase" VARCHAR,
                "Main_LegalTract" VARCHAR,
                "Main_LegalDistrict" VARCHAR,
                "Main_LegalMunicipality" VARCHAR,
                "Main_LegalCity" VARCHAR,
                "Main_LegalTownship" VARCHAR,
                "Main_LegalSTRSection" VARCHAR,
                "Main_LegalSTRTownship" VARCHAR,
                "Main_LegalSTRRange" VARCHAR,
                "Main_LegalSTRMeridian" VARCHAR,
                "Main_LegalSecTwnRngMer" VARCHAR,
                "Main_LegalRecordersMapReference" VARCHAR,
                "Main_LegalDescription" VARCHAR,
                "Main_LegalNeighborhoodSourceCode" VARCHAR,
                "Main_NoOfBuildings" INTEGER,
                "Main_LotSizeAcres" FLOAT,
                "Main_LotSizeSquareFeet" FLOAT,
                "Main_LotSizeFrontageFeet" FLOAT,
                "Main_LotSizeDepthFeet" FLOAT,
                "Main_LotSizeIRR" VARCHAR,
                "Main_LotSiteTopographyStndCode" VARCHAR,
                "Main_LoadID" BIGINT,
                "Main_PropertyAddressMatchcode" VARCHAR,
                "Main_PropertyAddressUnitDesignator" VARCHAR,
                "Main_PropertyAddressUnitNumber" VARCHAR,
                "Main_PropertyAddressCarrierRoute" VARCHAR,
                "Main_PropertyAddressGeoCodeMatchCode" VARCHAR,
                "Main_PropertyAddressLatitude" FLOAT,
                "Main_PropertyAddressLongitude" FLOAT,
                "Main_PropertyAddressCensusTractAndBlock" VARCHAR,
                "Main_PropertyAddressConfidenceScore" INTEGER,
                "Main_PropertyAddressCBSACode" INTEGER,
                "Main_PropertyAddressCBSADivisionCode" INTEGER,
                "Main_PropertyAddressMatchType" INTEGER,
                "Main_PropertyAddressDPV" VARCHAR,
                "Main_PropertyGeocodeQualityCode" VARCHAR,
                "Main_PropertyAddressQualityCode" VARCHAR,
                "Main_SubEdition" INTEGER,
                "Main_BatchID" INTEGER,
                "Main_BKFSPID" INTEGER,
                "Main_SourceChkSum" INTEGER,
                "Building_NoOfUnits" INTEGER,
                "Building_OccupancyStatusStndCode" VARCHAR,
                "Building_PropertyCountyLandUseDescription" VARCHAR,
                "Building_PropertyCountyLandUseCode" VARCHAR,
                "Building_PropertyLandUseStndCode" VARCHAR,
                "Building_PropertyStateLandUseDescription" VARCHAR,
                "Building_PropertyStateLandUseCode" VARCHAR,
                "Building_BuildingOrImprovementNumber" INTEGER,
                "Building_BuildingClassStndCode" VARCHAR,
                "Building_BuildingQualityStndCode" VARCHAR,
                "Building_BuildingQualityStndCodeOriginal" VARCHAR,
                "Building_BuildingConditionStndCode" VARCHAR,
                "Building_ArchitecturalStyleStndCode" VARCHAR,
                "Building_YearBuilt" INTEGER,
                "Building_EffectiveYearBuilt" INTEGER,
                "Building_YearRemodeled" INTEGER,
                "Building_NoOfStories" VARCHAR,
                "Building_TotalRooms" INTEGER,
                "Building_TotalBedrooms" INTEGER,
                "Building_TotalKitchens" INTEGER,
                "Building_FullBath" INTEGER,
                "Building_ThreeQuarterBath" FLOAT,
                "Building_HalfBath" FLOAT,
                "Building_QuarterBath" FLOAT,
                "Building_TotalCalculatedBathCount" FLOAT,
                "Building_TotalActualBathCount" FLOAT,
                "Building_BathSourceStndCode" VARCHAR,
                "Building_TotalBathPlumbingFixtures" INTEGER,
                "Building_RoofCoverStndCode" VARCHAR,
                "Building_RoofStructureTypeStndCode" VARCHAR,
                "Building_HeatingTypeorSystemStndCode" VARCHAR,
                "Building_AirConditioningTypeorSystemStndCode" VARCHAR,
                "Building_FoundationTypeStndCode" VARCHAR,
                "Building_ElevatorStndCode" VARCHAR,
                "Building_FireplaceFlag" VARCHAR,
                "Building_FirePlaceTypeStndCode" VARCHAR,
                "Building_FireplaceNumber" INTEGER,
                "Building_WaterStndCode" VARCHAR,
                "Building_SewerStndCode" VARCHAR,
                "Building_MortgageLenderName" VARCHAR,
                "Building_TimeshareStndCode" VARCHAR,
                "Building_Comments" VARCHAR,
                "Building_LoadID" BIGINT,
                "Building_StoryTypeStndCode" VARCHAR,
                "Building_FIPS" VARCHAR,
                "Building_BatchID" INTEGER,
                "Value_LandAssessedValue" FLOAT,
                "Value_ImprovementAssessedValue" FLOAT,
                "Value_TotalAssessedValue" FLOAT,
                "Value_AssessmentYear" INTEGER,
                "Value_LandMarketValue" FLOAT,
                "Value_ImprovementMarketValue" FLOAT,
                "Value_TotalMarketValue" FLOAT,
                "Value_MarketValueYear" INTEGER,
                "Value_LandAppraisalValue" FLOAT,
                "Value_ImprovementAppraisalValue" FLOAT,
                "Value_TotalAppraisalValue" FLOAT,
                "Value_AppraisalValueYear" INTEGER,
                "Value_FIPS" VARCHAR,
                "Value_BatchID" INTEGER,
                "TypeConstruction_BuildingOrImprovementNumber" INTEGER,
                "TypeConstruction_TypeConstructionStndCode" VARCHAR,
                "TypeConstruction_TypeConstructionPercent" FLOAT,
                "TypeConstruction_FIPS" VARCHAR,
                "TypeConstruction_BatchID" INTEGER,
                "InteriorWall_BuildingOrImprovementNumber" INTEGER,
                "InteriorWall_InteriorWallStndCode" VARCHAR,
                "InteriorWall_InteriorWallPercent" FLOAT,
                "InteriorWall_FIPS" VARCHAR,
                "InteriorWall_BatchID" INTEGER,
                "ExteriorWall_BuildingOrImprovementNumber" INTEGER,
                "ExteriorWall_ExteriorWallStndCode" VARCHAR,
                "ExteriorWall_ExteriorWallPercent" FLOAT,
                "ExteriorWall_FIPS" VARCHAR,
                "ExteriorWall_BatchID" INTEGER,
                "ZRowID" VARCHAR NOT NULL
                );
            """)

            cols = [                            "Main_ImportParcelID",
                "Main_FIPS",
                "Main_State",
                "Main_County",
                "Main_ValueCertDate",
                "Main_ExtractDate",
                "Main_Edition",
                "Main_ZVendorStndCode",
                "Main_AssessorParcelNumber",
                "Main_DupAPN",
                "Main_UnformattedAssessorParcelNumber",
                "Main_ParcelSequenceNumber",
                "Main_AlternateParcelNumber",
                "Main_OldParcelNumber",
                "Main_ParcelNumberTypeStndCode",
                "Main_RecordSourceStndCode",
                "Main_RecordTypeStndCode",
                "Main_ConfidentialRecordFlag",
                "Main_PropertyAddressSourceStndCode",
                "Main_PropertyHouseNumber",
                "Main_PropertyHouseNumberExt",
                "Main_PropertyStreetPreDirectional",
                "Main_PropertyStreetName",
                "Main_PropertyStreetSuffix",
                "Main_PropertyStreetPostDirectional",
                "Main_PropertyFullStreetAddress",
                "Main_PropertyCity",
                "Main_PropertyState",
                "Main_PropertyZip",
                "Main_PropertyZip4",
                "Main_OriginalPropertyFullStreetAddress",
                "Main_OriginalPropertyAddressLastline",
                "Main_PropertyBuildingNumber",
                "Main_PropertyZoningDescription",
                "Main_PropertyZoningSourceCode",
                "Main_CensusTract",
                "Main_TaxIDNumber",
                "Main_TaxAmount",
                "Main_TaxYear",
                "Main_TaxDelinquencyFlag",
                "Main_TaxDelinquencyAmount",
                "Main_TaxDelinquencyYear",
                "Main_TaxRateCodeArea",
                "Main_LegalLot",
                "Main_LegalLotStndCode",
                "Main_LegalOtherLot",
                "Main_LegalBlock",
                "Main_LegalSubdivisionCode",
                "Main_LegalSubdivisionName",
                "Main_LegalCondoProjectPUDDevName",
                "Main_LegalBuildingNumber",
                "Main_LegalUnit",
                "Main_LegalSection",
                "Main_LegalPhase",
                "Main_LegalTract",
                "Main_LegalDistrict",
                "Main_LegalMunicipality",
                "Main_LegalCity",
                "Main_LegalTownship",
                "Main_LegalSTRSection",
                "Main_LegalSTRTownship",
                "Main_LegalSTRRange",
                "Main_LegalSTRMeridian",
                "Main_LegalSecTwnRngMer",
                "Main_LegalRecordersMapReference",
                "Main_LegalDescription",
                "Main_LegalNeighborhoodSourceCode",
                "Main_NoOfBuildings",
                "Main_LotSizeAcres",
                "Main_LotSizeSquareFeet",
                "Main_LotSizeFrontageFeet",
                "Main_LotSizeDepthFeet",
                "Main_LotSizeIRR",
                "Main_LotSiteTopographyStndCode",
                "Main_LoadID",
                "Main_PropertyAddressMatchcode",
                "Main_PropertyAddressUnitDesignator",
                "Main_PropertyAddressUnitNumber",
                "Main_PropertyAddressCarrierRoute",
                "Main_PropertyAddressGeoCodeMatchCode",
                "Main_PropertyAddressLatitude",
                "Main_PropertyAddressLongitude",
                "Main_PropertyAddressCensusTractAndBlock",
                "Main_PropertyAddressConfidenceScore",
                "Main_PropertyAddressCBSACode",
                "Main_PropertyAddressCBSADivisionCode",
                "Main_PropertyAddressMatchType",
                "Main_PropertyAddressDPV",
                "Main_PropertyGeocodeQualityCode",
                "Main_PropertyAddressQualityCode",
                "Main_SubEdition",
                "Main_BatchID",
                "Main_BKFSPID",
                "Main_SourceChkSum",
                "Building_NoOfUnits",
                "Building_OccupancyStatusStndCode",
                "Building_PropertyCountyLandUseDescription",
                "Building_PropertyCountyLandUseCode",
                "Building_PropertyLandUseStndCode",
                "Building_PropertyStateLandUseDescription",
                "Building_PropertyStateLandUseCode",
                "Building_BuildingOrImprovementNumber",
                "Building_BuildingClassStndCode",
                "Building_BuildingQualityStndCode",
                "Building_BuildingQualityStndCodeOriginal",
                "Building_BuildingConditionStndCode",
                "Building_ArchitecturalStyleStndCode",
                "Building_YearBuilt",
                "Building_EffectiveYearBuilt",
                "Building_YearRemodeled",
                "Building_NoOfStories",
                "Building_TotalRooms",
                "Building_TotalBedrooms",
                "Building_TotalKitchens",
                "Building_FullBath",
                "Building_ThreeQuarterBath",
                "Building_HalfBath",
                "Building_QuarterBath",
                "Building_TotalCalculatedBathCount",
                "Building_TotalActualBathCount",
                "Building_BathSourceStndCode",
                "Building_TotalBathPlumbingFixtures",
                "Building_RoofCoverStndCode",
                "Building_RoofStructureTypeStndCode",
                "Building_HeatingTypeorSystemStndCode",
                "Building_AirConditioningTypeorSystemStndCode",
                "Building_FoundationTypeStndCode",
                "Building_ElevatorStndCode",
                "Building_FireplaceFlag",
                "Building_FirePlaceTypeStndCode",
                "Building_FireplaceNumber",
                "Building_WaterStndCode",
                "Building_SewerStndCode",
                "Building_MortgageLenderName",
                "Building_TimeshareStndCode",
                "Building_Comments",
                "Building_LoadID",
                "Building_StoryTypeStndCode",
                "Building_FIPS",
                "Building_BatchID",
                "Value_LandAssessedValue",
                "Value_ImprovementAssessedValue",
                "Value_TotalAssessedValue",
                "Value_AssessmentYear",
                "Value_LandMarketValue",
                "Value_ImprovementMarketValue",
                "Value_TotalMarketValue",
                "Value_MarketValueYear",
                "Value_LandAppraisalValue",
                "Value_ImprovementAppraisalValue",
                "Value_TotalAppraisalValue",
                "Value_AppraisalValueYear",
                "Value_FIPS",
                "Value_BatchID",
                "TypeConstruction_BuildingOrImprovementNumber",
                "TypeConstruction_TypeConstructionStndCode",
                "TypeConstruction_TypeConstructionPercent",
                "TypeConstruction_FIPS",
                "TypeConstruction_BatchID",
                "InteriorWall_BuildingOrImprovementNumber",
                "InteriorWall_InteriorWallStndCode",
                "InteriorWall_InteriorWallPercent",
                "InteriorWall_FIPS",
                "InteriorWall_BatchID",
                "ExteriorWall_BuildingOrImprovementNumber",
                "ExteriorWall_ExteriorWallStndCode",
                "ExteriorWall_ExteriorWallPercent",
                "ExteriorWall_FIPS",
                "ExteriorWall_BatchID",
                "ZRowID"]

            sel = src.execute("""
                SELECT
                            "Main_ImportParcelID",
                "Main_FIPS",
                "Main_State",
                "Main_County",
                "Main_ValueCertDate",
                "Main_ExtractDate",
                "Main_Edition",
                "Main_ZVendorStndCode",
                "Main_AssessorParcelNumber",
                "Main_DupAPN",
                "Main_UnformattedAssessorParcelNumber",
                "Main_ParcelSequenceNumber",
                "Main_AlternateParcelNumber",
                "Main_OldParcelNumber",
                "Main_ParcelNumberTypeStndCode",
                "Main_RecordSourceStndCode",
                "Main_RecordTypeStndCode",
                "Main_ConfidentialRecordFlag",
                "Main_PropertyAddressSourceStndCode",
                "Main_PropertyHouseNumber",
                "Main_PropertyHouseNumberExt",
                "Main_PropertyStreetPreDirectional",
                "Main_PropertyStreetName",
                "Main_PropertyStreetSuffix",
                "Main_PropertyStreetPostDirectional",
                "Main_PropertyFullStreetAddress",
                "Main_PropertyCity",
                "Main_PropertyState",
                "Main_PropertyZip",
                "Main_PropertyZip4",
                "Main_OriginalPropertyFullStreetAddress",
                "Main_OriginalPropertyAddressLastline",
                "Main_PropertyBuildingNumber",
                "Main_PropertyZoningDescription",
                "Main_PropertyZoningSourceCode",
                "Main_CensusTract",
                "Main_TaxIDNumber",
                "Main_TaxAmount",
                "Main_TaxYear",
                "Main_TaxDelinquencyFlag",
                "Main_TaxDelinquencyAmount",
                "Main_TaxDelinquencyYear",
                "Main_TaxRateCodeArea",
                "Main_LegalLot",
                "Main_LegalLotStndCode",
                "Main_LegalOtherLot",
                "Main_LegalBlock",
                "Main_LegalSubdivisionCode",
                "Main_LegalSubdivisionName",
                "Main_LegalCondoProjectPUDDevName",
                "Main_LegalBuildingNumber",
                "Main_LegalUnit",
                "Main_LegalSection",
                "Main_LegalPhase",
                "Main_LegalTract",
                "Main_LegalDistrict",
                "Main_LegalMunicipality",
                "Main_LegalCity",
                "Main_LegalTownship",
                "Main_LegalSTRSection",
                "Main_LegalSTRTownship",
                "Main_LegalSTRRange",
                "Main_LegalSTRMeridian",
                "Main_LegalSecTwnRngMer",
                "Main_LegalRecordersMapReference",
                "Main_LegalDescription",
                "Main_LegalNeighborhoodSourceCode",
                "Main_NoOfBuildings",
                "Main_LotSizeAcres",
                "Main_LotSizeSquareFeet",
                "Main_LotSizeFrontageFeet",
                "Main_LotSizeDepthFeet",
                "Main_LotSizeIRR",
                "Main_LotSiteTopographyStndCode",
                "Main_LoadID",
                "Main_PropertyAddressMatchcode",
                "Main_PropertyAddressUnitDesignator",
                "Main_PropertyAddressUnitNumber",
                "Main_PropertyAddressCarrierRoute",
                "Main_PropertyAddressGeoCodeMatchCode",
                "Main_PropertyAddressLatitude",
                "Main_PropertyAddressLongitude",
                "Main_PropertyAddressCensusTractAndBlock",
                "Main_PropertyAddressConfidenceScore",
                "Main_PropertyAddressCBSACode",
                "Main_PropertyAddressCBSADivisionCode",
                "Main_PropertyAddressMatchType",
                "Main_PropertyAddressDPV",
                "Main_PropertyGeocodeQualityCode",
                "Main_PropertyAddressQualityCode",
                "Main_SubEdition",
                "Main_BatchID",
                "Main_BKFSPID",
                "Main_SourceChkSum",
                "Building_NoOfUnits",
                "Building_OccupancyStatusStndCode",
                "Building_PropertyCountyLandUseDescription",
                "Building_PropertyCountyLandUseCode",
                "Building_PropertyLandUseStndCode",
                "Building_PropertyStateLandUseDescription",
                "Building_PropertyStateLandUseCode",
                "Building_BuildingOrImprovementNumber",
                "Building_BuildingClassStndCode",
                "Building_BuildingQualityStndCode",
                "Building_BuildingQualityStndCodeOriginal",
                "Building_BuildingConditionStndCode",
                "Building_ArchitecturalStyleStndCode",
                "Building_YearBuilt",
                "Building_EffectiveYearBuilt",
                "Building_YearRemodeled",
                "Building_NoOfStories",
                "Building_TotalRooms",
                "Building_TotalBedrooms",
                "Building_TotalKitchens",
                "Building_FullBath",
                "Building_ThreeQuarterBath",
                "Building_HalfBath",
                "Building_QuarterBath",
                "Building_TotalCalculatedBathCount",
                "Building_TotalActualBathCount",
                "Building_BathSourceStndCode",
                "Building_TotalBathPlumbingFixtures",
                "Building_RoofCoverStndCode",
                "Building_RoofStructureTypeStndCode",
                "Building_HeatingTypeorSystemStndCode",
                "Building_AirConditioningTypeorSystemStndCode",
                "Building_FoundationTypeStndCode",
                "Building_ElevatorStndCode",
                "Building_FireplaceFlag",
                "Building_FirePlaceTypeStndCode",
                "Building_FireplaceNumber",
                "Building_WaterStndCode",
                "Building_SewerStndCode",
                "Building_MortgageLenderName",
                "Building_TimeshareStndCode",
                "Building_Comments",
                "Building_LoadID",
                "Building_StoryTypeStndCode",
                "Building_FIPS",
                "Building_BatchID",
                "Value_LandAssessedValue",
                "Value_ImprovementAssessedValue",
                "Value_TotalAssessedValue",
                "Value_AssessmentYear",
                "Value_LandMarketValue",
                "Value_ImprovementMarketValue",
                "Value_TotalMarketValue",
                "Value_MarketValueYear",
                "Value_LandAppraisalValue",
                "Value_ImprovementAppraisalValue",
                "Value_TotalAppraisalValue",
                "Value_AppraisalValueYear",
                "Value_FIPS",
                "Value_BatchID",
                "TypeConstruction_BuildingOrImprovementNumber",
                "TypeConstruction_TypeConstructionStndCode",
                "TypeConstruction_TypeConstructionPercent",
                "TypeConstruction_FIPS",
                "TypeConstruction_BatchID",
                "InteriorWall_BuildingOrImprovementNumber",
                "InteriorWall_InteriorWallStndCode",
                "InteriorWall_InteriorWallPercent",
                "InteriorWall_FIPS",
                "InteriorWall_BatchID",
                "ExteriorWall_BuildingOrImprovementNumber",
                "ExteriorWall_ExteriorWallStndCode",
                "ExteriorWall_ExteriorWallPercent",
                "ExteriorWall_FIPS",
                "ExteriorWall_BatchID",
                "ZRowID"
                FROM zasmt WHERE Main_County in ('LOS ANGELES', 'RIVERSIDE', 'SAN BERNARDINO', 'IMPERIAL', 'VENTURA', 'ORANGE')
            """)

            meta = sq.MetaData(trans)

            with tqdm.tqdm() as pbar:
                while (row := sel.fetchone()) is not None:
                    trans.execute(sq.insert(sq.Table('zasmt', meta, autoload=True, schema='diss')).values(row))
                    pbar.update()
